export const IGNORE_LINKS = [
	"https://cms.ecda.gov.sg/preschool",
	"https://cms.ecda.gov.sg/prweb/SubsidyCalculator/",
	"https://services2.hdb.gov.sg/webapp/BP13EligCheck/BP13SHome?strSystem=CHECK",
	"https://services2.hdb.gov.sg/webapp/BP27AWHLEApplication/BP27SHome",
	"http://services2.hdb.gov.sg/webapp/BF08CESS/Index.jsp",
	"https://www.chas.sg/WorkArea/linkit.aspx?LinkIdentifier=id&ItemID=1548&libID=1812",
	"http://www.chas.sg/apply/",
	"https://beta.moe.gov.sg/fees-assistance-awards-scholarships/psea/",
	"https://www.babybonus.msf.gov.sg/parent-helper/",
	"https://www.tech.gov.sg/report_vulnerability/",
	"https://apps.apple.com/sg/app/moments-of-life/id1383218758",
	"https://play.google.com/store/apps/details?id=sg.gov.app.mol&hl=en_SG",
	"https://tech.gov.sg/report_vulnerability",
	"https://www.gov.sg",
	"https://t.me/OMWNetworkConnects",
	"https://www.nyc.gov.sg/omw/letstalk",
	"https://www.nyc.gov.sg/omw/connect",
	"https://www.tal.sg/tadm/know-your-options",
];

export const URL_EXCLUSIONS = [
	".png",
	".jpg",
	".pdf",
	"services2.hdb.gov.sg",
	"https://t.me/",
	"www.life.gov.sg",
	"go.gov.sg",
];
